### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Would also be good to clarify in the description and readme what the modification is, i.e. what makes it different from https://kitspace.org/boards/github.com/drspangle/infidel-sensor/

### CODE REVIEW

**Comment by m3cinc** [comment]
I have updated and revised further the board  and wire routing. Included newer files and documented the difference with prior design.

**Comment by kasbah** [comment]
Ok, but the changes I requested still need to be made to add the board to KItspace:

- Add a kitspace.yaml which points at bom and gerber folder
- Drill file needs to be moved to the same folder

**Comment by m3cinc** [comment]
Please check that these have been met and let me know. Thanks

**Comment by kasbah** [comment]
1-click-bom.csv seems to be missing. Looks good otherwise.

**Comment by m3cinc** [comment]
Emmanuel,
should be fixed now... thanks for your help. I'm very novice at this!
Marc

**Comment by kasbah** [comment]
No problem. One last thing would be to mention the difference earlier in the  `summary:` as it gets cut off on the search page.

image

**Pull request closed without merging**
